# Generated by Django 2.2.5 on 2019-12-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Can',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('canid', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
            ],
        ),
    ]
