# Generated by Django 2.2.5 on 2019-12-11 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requestHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='can',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
