# Generated by Django 2.2.5 on 2019-12-13 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requestHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='remoteOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('ip', models.CharField(blank=None, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='can',
            name='accuracy',
            field=models.CharField(blank=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='can',
            name='adjacents',
            field=models.CharField(blank=None,  max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='can',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='can',
            name='lat',
            field=models.CharField(blank=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='can',
            name='lon',
            field=models.CharField(blank=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='can',
            name='ip',
            field=models.CharField(blank=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='can',
            name='level',
            field=models.FloatField(blank=None),
        ),
        migrations.AlterField(
            model_name='can',
            name='status',
            field=models.IntegerField(blank=None),
        ),
    ]
