# Generated by Django 2.2.5 on 2019-12-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestHandler', '0002_auto_20191213_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='can',
            name='adjacents',
        ),
    ]
